spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

---

spring:
  profiles: default
  jpa:
    database: HSQL

---

spring:
  profiles: docker
  jpa:
    database: MYSQL
  datasource:
      url: jdbc:mysql://${mysql.port.3306.tcp.addr}:${mysql.port.3306.tcp.port}/languages
      username: ${mysql.username}
      password: ${mysql.password}
      driver-class-name: com.mysql.jdbc.Driver

---

spring:
  profiles: lattice
  jpa:
    database: MYSQL
  datasource:
      url: jdbc:mysql://192.168.59.103:32772/languages
      username: ${mysql.username}
      password: ${mysql.password}
      driver-class-name: com.mysql.jdbc.Driver